### ISSUE TITLE
Download OpenSpending datasets as a data.frame object

### ISSUE THREAD

**Issue by fontanon** [mihi-tr/r-openspending#12]
R-project's data.frames are one of best objects for dealing with data that R can provide.

Automating the download of OpenSpending's datasets as dataframes would make easier lots of operations that lists can't.

**Comment by mihi-tr** [comment]
@fontanon there are two functions `openspending.as.data.frame` and `openspending.list.to.data.frame` that do list conversions - do you think these are enough? Or would you rather have the functions give out data frames per default?

**Comment by fontanon** [comment]
Didn't realized of those functions and they work great!
No need to convert to data.frame as by-default behaviour.

Here's an use case: merging two OpenSpending datasets to compare revenues
https://gist.github.com/fontanon/6341178

**Comment by mihi-tr** [comment]
Great, thanks!
